benji_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('my_finances/', include('my_finances.urls')),
    path('accounts/', include('accounts.urls')),
    path('budget_section/', include('budget_section.urls')),
    path('savings_section/', include('savings_section.urls')),
    path('ai/', include('ai_features.urls')),
    path('tax/', include('tax_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

my_finances/urls.py
from django.urls import path

from my_finances import views

app_name = 'my_finances'

urlpatterns = [
    # Income_urls
    path('income_list/', views.IncomeListView.as_view(), name='income_list'),
    path('income_detail/<pk>', views.IncomeDetailView.as_view(), name='income_detail'),
    path('income_create/', views.IncomeCreateView.as_view(), name='income_create'),
    path('income_update/<pk>', views.IncomeUpdateView.as_view(), name='income_update'),
    path('income_delete/<pk>', views.IncomeDeleteView.as_view(), name='income_delete'),
    # Outcome_urls
    path('outcome_list/', views.OutcomeListView.as_view(), name='outcome_list'),
    path('outcome_detail/<pk>', views.OutcomeDetailView.as_view(), name='outcome_detail'),
    path('outcome_create/', views.OutcomeCreateView.as_view(), name='outcome_create'),
    path('outcome_update/<pk>', views.OutcomeUpdateView.as_view(), name='outcome_update'),
    path('outcome_delete/<pk>', views.OutcomeDeleteView.as_view(), name='outcome_delete'),

    # balance_urls
    path('balance_list/', views.BalanceListView.as_view(), name='balance_list'),
    path('balance_detail/<pk>', views.BalanceDetailView.as_view(), name='balance_detail'),
    path('balance_create/', views.BalanceCreateView.as_view(), name='balance_create'),
    path('balance_update/<pk>', views.BalanceUpdateView.as_view(), name='balance_update'),
    path('balance_delete/<pk>', views.BalanceDeleteView.as_view(), name='balance_delete'),

    # dashboard_urls
    path('current_period/', views.current_period, name='current_period'),
    path('year_overview/', views.year_overview, name='year_overview'),
    path('get_summary_tiles/', views.get_summary_tiles, name='get_summary_tiles'),
    path('get_year_chart/', views.get_year_chart, name='get_year_chart'),
    path('get_income_or_outcome_by_type/', views.get_income_or_outcome_by_type, name='get_income_or_outcome_by_type'),

]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard')
]

my_finances/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Income(models.Model):
    class ITypes(models.IntegerChoices):
        SAL = 1, "SALARY"
        BON = 2, "BONUS"
        GIF = 3, "GIFT"
        OTH = 4, "OTHER"
        SAV = 5, "SAVINGS"

    class RInterval(models.IntegerChoices):
        NA = 1, 'N/A'
        DAY = 2, 'DAYS'
        WEK = 3, 'WEEKS'
        MON = 4, 'MONTHS'
        YEA = 5, 'YEARS'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_incomes')
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    type = models.PositiveSmallIntegerField(choices=ITypes.choices)
    repetitive = models.BooleanField(default=False)
    repetition_interval = models.PositiveSmallIntegerField(choices=RInterval.choices, default=1)
    repetition_time = models.PositiveSmallIntegerField(default=0)
    repetition_end = models.DateField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Income {self.id} - {self.type} - {self.date.strftime("%Y/%m/%d")}'

    class Meta:
        verbose_name_plural = 'incomes'


class Outcome(models.Model):
    class OTypes(models.IntegerChoices):
        REN = 1, "RENT"
        BIL = 2, "BILLS"
        CAR = 3, "CAR"
        TRA = 4, "TRAVEL"
        HEA = 5, "HEALTH"
        GRO = 6, "GROCERIES"
        FUN = 7, "FUN"
        CLO = 8, "CLOTHES"
        CHA = 9, "CHARITY"
        SAV = 10, "SAVINGS"

    class RInterval(models.IntegerChoices):
        NA = 1, 'N/A'
        DAY = 2, 'DAYS'
        WEK = 3, 'WEEKS'
        MON = 4, 'MONTHS'
        YEA = 5, 'YEARS'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_outcomes')
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    type = models.PositiveSmallIntegerField(choices=OTypes.choices)
    repetitive = models.BooleanField(default=False)
    repetition_interval = models.PositiveSmallIntegerField(choices=RInterval.choices, default=1)
    repetition_time = models.PositiveSmallIntegerField(default=0)
    repetition_end = models.DateField(null=True)
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Outcome {self.id} - {self.type} - {self.date.strftime("%Y/%m/%d")}'

    class Meta:
        verbose_name_plural = 'outcomes'


class Balance(models.Model):
    class BType(models.IntegerChoices):
        CUR = 1, "CURRENT"
        SAV = 2, "SAVINGS"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_balances')
    value = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.PositiveSmallIntegerField(choices=BType.choices)
    date = models.DateField()
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Balance {self.id} - {self.type}'

    class Meta:
        verbose_name_plural = 'balances'

my_finances/views.py
from datetime import date, timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from my_finances.forms import IncomeForm, OutcomeForm, BalanceForm
from my_finances.helpers import calculate_repetitive_total
from my_finances.models import Income, Outcome, Balance


@method_decorator(login_required, name='dispatch')
class IncomeListView(ListView):
    model = Income
    paginate_by = 100
    template_name = 'my_finances/balance_income_outcome_list.html'
    extra_context = {'list_what': 'Income'}

    def get_queryset(self):
        user = self.request.user
        return Income.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class IncomeDetailView(DetailView):
    model = Income
    template_name = 'my_finances/balance_income_outcome_detail.html'
    extra_context = {'detail_what': 'Income'}

    # queryset = Income.objects.all()

    def get_queryset(self):
        user = self.request.user
        return Income.objects.filter(user=user)
    # context_object_name = 'income'


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class IncomeCreateView(CreateView):
    model = Income
    form_class = IncomeForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Add Income'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Income created successfully!')
        return reverse_lazy('my_finances:income_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class IncomeUpdateView(UpdateView):
    model = Income
    form_class = IncomeForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Update Income'}

    def get_queryset(self):
        user = self.request.user
        return Income.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Income updated successfully!')
        return reverse('my_finances:income_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class IncomeDeleteView(DeleteView):
    model = Income
    template_name = 'my_finances/balance_income_outcome_confirm_delete.html'
    extra_context = {'delete_what': 'Income'}

    # template_name_suffix = '_delete_form'
    # queryset = Income.objects.all()

    def get_queryset(self):
        user = self.request.user
        return Income.objects.filter(user=user)

    # context_object_name = 'income'

    def get_success_url(self):
        messages.success(self.request, 'Income deleted successfully!')
        return reverse_lazy('my_finances:income_list')


class OutcomeListView(ListView):
    model = Outcome
    paginate_by = 100
    template_name = 'my_finances/balance_income_outcome_list.html'
    extra_context = {'list_what': 'Outcome'}

    def get_queryset(self):
        user = self.request.user
        return Outcome.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
class OutcomeDetailView(DetailView):
    model = Outcome
    template_name = 'my_finances/balance_income_outcome_detail.html'
    extra_context = {'detail_what': 'Outcome'}

    def get_queryset(self):
        user = self.request.user
        return Outcome.objects.filter(user=user)


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class OutcomeCreateView(CreateView):
    model = Outcome
    form_class = OutcomeForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Add Outcome'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Outcome created successfully!')
        return reverse_lazy('my_finances:outcome_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class OutcomeUpdateView(UpdateView):
    model = Outcome
    form_class = OutcomeForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Update Outcome'}

    def get_queryset(self):
        user = self.request.user
        return Outcome.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Outcome updated successfully!')
        return reverse('my_finances:outcome_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class OutcomeDeleteView(DeleteView):
    model = Outcome
    template_name = 'my_finances/balance_income_outcome_confirm_delete.html'
    extra_context = {'delete_what': 'Outcome'}

    def get_queryset(self):
        user = self.request.user
        return Outcome.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Outcome deleted successfully!')
        return reverse_lazy('my_finances:outcome_list')


@method_decorator(login_required, name='dispatch')
class BalanceListView(ListView):
    model = Balance
    paginate_by = 100
    template_name = 'my_finances/balance_income_outcome_list.html'
    extra_context = {'list_what': 'Balance'}

    def get_queryset(self):
        user = self.request.user
        return Balance.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BalanceDetailView(DetailView):
    model = Balance
    template_name = 'my_finances/balance_income_outcome_detail.html'
    extra_context = {'detail_what': 'Balance'}

    def get_queryset(self):
        user = self.request.user
        return Balance.objects.filter(user=user)


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BalanceCreateView(CreateView):
    model = Balance
    form_class = BalanceForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Add Balance'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Balance created successfully!')
        return reverse_lazy('my_finances:balance_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BalanceUpdateView(UpdateView):
    model = Balance
    form_class = BalanceForm
    template_name = 'my_finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Update Balance'}

    def get_queryset(self):
        user = self.request.user
        return Balance.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Balance updated successfully!')
        return reverse_lazy('my_finances:balance_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BalanceDeleteView(DeleteView):
    model = Balance
    template_name = 'my_finances/balance_income_outcome_confirm_delete.html'
    extra_context = {'delete_what': 'Balance'}

    def get_queryset(self):
        user = self.request.user
        return Balance.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Balance deleted successfully!')
        return reverse_lazy('my_finances:balance_list')


@login_required()
def current_period(request):
    make_calls = True
    last_balance = Balance.objects.filter(user=request.user, type=1).order_by('-date').first()
    if not last_balance:
        messages.warning(request, 'No current balance has been recorded. '
                                  'Please add at least one current balance record.')
        make_calls = False
    return render(request, 'my_finances/current_period.html', context={'make_calls': make_calls})


@login_required
def year_overview(request):
    make_calls = True
    last_balance = Balance.objects.filter(user=request.user, type=1).order_by('-date').first()
    last_savings_balance = Balance.objects.filter(user=request.user, type=2).order_by('-date').first()
    if last_balance is None and last_savings_balance is None:
        messages.warning(request, 'No current balance has been recorded. '
                                  'Please add at least one current balance record.')
        make_calls = False
    return render(request, 'my_finances/year_overview.html', context={'make_calls': make_calls})


@login_required
def get_summary_tiles(request):
    today = date.today()
    last_balance = Balance.objects.filter(user=request.user, type=1).order_by('-date').first()
    if not last_balance:
        return JsonResponse({'error': 'No current balance has been recorded. '
                                      'Please add at least one current balance record.'})

templates/my_finances/balance_income_outcome_confirm_delete.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ delete_what }} - {{ object.id }}</h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>

    </div>
</div>
{% endblock %}

templates/my_finances/balance_income_outcome_detail.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">

    <div class="col-lg-8 mx-auto">
        <h1>{{detail_what}} {{object.id}}</h1>
        <ul>
            <li>Date: {{object.date|date}}</li>
            <li> Type: {{object.get_type_display}}</li>
            <li> Value: ${{object.value}}</li>
        {% if detail_what != 'Balance' %}
            <li> Repetitive: {{object.repetitive}}</li>
            {% if object.repetitive %}
            <li> Every {{object.repetition_time}} {{income.get_repetition_interval_display}}</li>
            {% endif %}
        {% endif %}
        </ul>
        {% if detail_what == 'Income' %}
        <a href="{% url 'my_finances:income_update' object.id %}">Update</a>
        <a href="{% url 'my_finances:income_delete' object.id %}">Delete</a>
        {% elif detail_what == 'Outcome' %}
        <a href="{% url 'my_finances:outcome_update' object.id %}">Update</a>
        <a href="{% url 'my_finances:outcome_delete' object.id %}">Delete</a>
        {% else %}
        <a href="{% url 'my_finances:balance_update' object.id %}">Update</a>
        <a href="{% url 'my_finances:balance_delete' object.id %}">Delete</a>
        {% endif %}


    </div>
</div>
{% endblock %}

templates/my_finances/balance_income_outcome_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ header }}</h1>

        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save">
        </form>

    </div>
</div>
{% endblock %}

templates/my_finances/balance_income_outcome_list.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">

            <h1>{{ list_what }} list</h1>

        </div>
    </div>

    <!-- Table-->
    <div class="row">
        <div class="col-lg-8 mx-auto table-responsive">

            {% if object_list %}
                <table id="list-table" class="table">
                    <thead>
                    <tr>
                        <th scope="col">Date</th>
                        {% if list_what != 'Balance' %}
                            <th scope="col">End</th>
                        {% endif %}
                        <th scope="col">Type</th>
                        <th scope="col">Value</th>
                        {% if list_what != 'Balance' %}
                            <th scope="col">Repetition</th>
                        {% endif %}
                        <th scope="col">Comment</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody id="table-body">
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.date|date:"Y/m/d" }}</td>
                            {% if list_what != 'Balance' %}
                                <td>{{ object.repetition_end|date:"Y/m/d" }}</td>
                            {% endif %}
                            <td>{{ object.get_type_display }}</td>
                            <td>{{ object.value }}</td>
                            {% if list_what != 'Balance' %}
                                <td>
                                    {% if object.repetitive %}
                                        every {{ object.repetition_time }} {{ object.get_repetition_interval_display }}
                                    {% endif %}
                                </td>
                            {% endif %}
                            <td>{{ object.comment }}</td>
                            <td>
                                {% if list_what == 'Income' %}
                                    <a href="{% url 'my_finances:income_detail' object.pk %}">
                                {% elif list_what == 'Outcome' %}
                                    <a href="{% url 'my_finances:outcome_detail' object.pk %}">
                                {% else %}
                                    <a href="{% url 'my_finances:balance_detail' object.pk %}">
                                {% endif %}
                                <i class="fas fa-search-plus"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Nothing to show
            {% endif %}

        </div>
    </div>

{% endblock %}

{% block js %}
    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#list-table').DataTable(
                {
                    order: [[0, "desc"]],
                    columns: [
                        {name: "Date", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "End", orderable: true},
                        {% endif %}
                        {name: "Type", orderable: true},
                        {name: "Value", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "Repetition", orderable: true},
                        {% endif %}
                        {name: "Comment", orderable: true},
                        {name: "Details", orderable: false},
                    ]
                }
            );
        })
    </script>
{% endblock %}

templates/my_finances/current_period.html
{% extends 'base2.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Current Year</h1>
    </div>

 {% if make_calls %}
    <div class="row" id="summary_tiles">

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Last Balance Check
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800" id="last_balance_value"></div>
                            <div class="text-black-50 small" id="last_balance_date"><i><b></b></i></div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Estimated Balance Now
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800" id="estimated_balance"></div>
                        </div>
                        <div class="col-auto">
                             <i class="fas fa-money fa-3x text-gray-300"><span>₹</span></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1" >Estimated Income
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="total_income"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-money fa-3x text-gray-300"><span>₹</span></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Estimated Outcome
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800" id="total_outcome"></div>
                        </div>
                        <div class="col-auto">
                             <i class="fas fa-money fa-3x text-gray-300"><span>₹</span></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="income_outcome_by_type">
        <div class="col-12 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Income by Type</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="income_by_type"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Outcome by Type</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="outcome_by_type"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <b>No data available!</b>
{% endif %}

{% endblock %}

{% block js %}
    <!-- Page level plugins -->
    {% if make_calls %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"
        integrity="sha512-Wt1bJGtlnMtGP0dqNFH1xlkLBNpEodaiQ8ZN5JLA5wpc1sUlk/O5uuOMNgvzddzkpvZ9GLyYNa8w2s7rqiTk5Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/my_finances/common_chart.js' %}?v={% now 'U' %}"></script>
<script src="{% static 'js/my_finances/current_period_chart.js' %}?v={% now 'U' %}"></script>
    {% endif %}
{% endblock %}