benji_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('my_finances/', include('my_finances.urls')),
    path('accounts/', include('accounts.urls')),
    path('budget_section/', include('budget_section.urls')),
    path('savings_section/', include('savings_section.urls')),
    path('ai/', include('ai_features.urls')),
    path('tax/', include('tax_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

budget_section/urls.py
from django.urls import path

from budget_section.views import CategoryCreateView, TransactionUpdateView, TransactionCreateView, CategoryUpdateView, \
    BudgetCreateView, BudgetUpdateView, BudgetListView, CategoryListView, BudgetDeleteView, \
    CategoryDeleteView, TransactionListView, TransactionDeleteView, CategoryDetailView, TransactionDetailView, \
    BudgetDetailView, GetSummaryTiles

app_name = 'budget_section'

urlpatterns = [
    # CATEGORIES URLS
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<slug:slug>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/detail/<slug:slug>/', CategoryDetailView.as_view(), name='category_details'),
    path('category/delete/<slug:slug>/', CategoryDeleteView.as_view(), name='category_delete'),
    # TRANSACTIONS URLS
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transaction/create/', TransactionCreateView.as_view(), name='transaction_create'),
    path('transaction/update/<slug:slug>/', TransactionUpdateView.as_view(), name='transaction_update'),
    path('transaction/detail/<slug:slug>/', TransactionDetailView.as_view(), name='transaction_details'),
    path('transaction/delete/<slug:slug>/', TransactionDeleteView.as_view(), name='transaction_delete'),
    # BUDGET URLS
    path('budgets/', BudgetListView.as_view(), name='budget_list'),
    path('budget/create/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/update/<slug:slug>/', BudgetUpdateView.as_view(), name='budget_update'),
    path('budget/detail/<slug:slug>/', BudgetDetailView.as_view(), name='budget_details'),
    path('budget/delete/<slug:slug>/', BudgetDeleteView.as_view(), name='budget_delete'),
    # DASHBOARD URLS
    path('budget/current_period/budget_name/<slug:slug>', GetSummaryTiles.as_view(), name='budget_summary'),
    # path('budget/current_period/<slug:slug>',  BudgetCategoryView.as_view(), name='budget-category'),

]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard')
]

budget_section/forms.py
from datetime import date
from django import forms
from django.core.exceptions import ValidationError

from .models import Category, Transaction, Budget


class DateInput(forms.DateInput):
    input_type = 'date'


class CategoryForm(forms.ModelForm):
    def is_valid(self):
        is_valid = super().is_valid()
        # add custom validation logic for the name field
        if 'name' in self.cleaned_data:
            name = self.cleaned_data['name']
            if name.startswith('X'):  # name should not start with 'X'
                self.add_error('name', 'Name should not start with X')
                is_valid = False

        return is_valid

    class Meta:
        model = Category
        fields = ['name', 'description']

    def clean_name(self):
        name = self.cleaned_data['name']
        if any(char.isdigit() for char in name):  # check if name contains any digits
            raise ValidationError("Name should not contain numbers")
        return name


class TransactionForm(forms.ModelForm):
    def is_valid(self):
        is_valid = super().is_valid()
        # add custom validation logic for the name field
        if 'title' in self.cleaned_data:
            name = self.cleaned_data['title']
            if name.startswith('X'):  # name should not start with 'X'
                self.add_error(field='title', error='Name should not start with X')
                is_valid = False
        if 'amount' in self.cleaned_data:
            amount = self.cleaned_data['amount']
            budget = self.cleaned_data['budget']
            if amount <= 0:
                self.add_error(field='amount', error='Amount must be greater than zero')
                is_valid = False
            elif amount != int(amount):
                self.add_error(field='amount', error='Amount must be a whole number')
                is_valid = False
            elif amount > budget.amount:
                self.add_error(field='amount', error='Amount cannot be greater than budget amount')
                is_valid = False
        return is_valid

    class Meta:
        model = Transaction
        fields = ['title', 'amount', 'category', 'budget', 'date', 'notes']

    date = forms.DateField(widget=DateInput, initial=date.today())

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount <= 0:
            raise ValidationError("Amount must be greater than zero")
        elif amount != int(amount):
            raise ValidationError("Amount must be a whole number")
        return amount


class BudgetForm(forms.ModelForm):
    def is_valid(self):
        is_valid = super().is_valid()
        # add custom validation logic for the name field
        if 'name' in self.cleaned_data:
            name = self.cleaned_data['name']
            if name.startswith('X'):  # name should not start with 'X'
                self.add_error(field='name', error='Name should not start with X')
                is_valid = False
        if 'start_date' in self.cleaned_data and 'end_date' in self.cleaned_data:
            start_date = self.cleaned_data['start_date']
            end_date = self.cleaned_data['end_date']
            if end_date <= start_date:
                self.add_error(field='end_date', error='End date must be greater than start date')
                is_valid = False
            if start_date >= end_date:
                self.add_error(field='start_date', error='Start date must be less than end date')
                is_valid = False

        return is_valid

    class Meta:
        model = Budget
        fields = ['name', 'amount', 'start_date', 'end_date']

    start_date = forms.DateField(widget=DateInput, initial=date.today())
    end_date = forms.DateField(widget=DateInput)

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount <= 0:
            raise ValidationError("Amount must be greater than zero")
        elif amount != int(amount):
            raise ValidationError("Amount must be a whole number")
        return amount

    def clean_end_date(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if end_date <= start_date:
            raise ValidationError("End date must be greater than start date")
        if start_date >= end_date:
            raise ValidationError("Start date must be less than end date")

        return end_date

budget_section/views.py
import datetime
import json
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView

from .forms import CategoryForm, TransactionForm, BudgetForm
from .models import Category, Transaction, Budget


# BUDGET
@method_decorator(login_required, name='dispatch')
class BudgetListView(ListView):
    model = Budget
    template_name = 'budget_section/category_transaction_budget_list.html'
    paginate_by = 100
    extra_context = {'list_what': 'Budget'}

    def get_queryset(self):
        user = self.request.user
        return Budget.objects.filter(user=user).order_by('-start_date')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BudgetCreateView(CreateView):
    model = Budget
    form_class = BudgetForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Add Budget'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Budget created successfully!')
        return reverse_lazy('budget_section:budget_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BudgetUpdateView(UpdateView):
    model = Budget
    form_class = BudgetForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Update Budget'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Budget updated successfully!')
        return reverse_lazy('budget_section:budget_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BudgetDetailView(DetailView):
    model = Budget
    template_name = 'budget_section/category_transaction_budget_detail.html'
    extra_context = {'detail_what': 'Budget'}

    def get_queryset(self):
        user = self.request.user
        return Budget.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class BudgetDeleteView(DeleteView):
    model = Budget
    template_name = 'budget_section/category_transaction_budget_delete.html'
    extra_context = {'delete_what': 'Budget'}

    def get_queryset(self):
        user = self.request.user
        return Budget.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Budget deleted successfully!')
        return reverse_lazy('budget_section:budget_list')


# CATEGORY
@method_decorator(login_required, name='dispatch')
class CategoryListView(ListView):
    model = Category
    template_name = 'budget_section/category_transaction_budget_list.html'
    paginate_by = 100
    extra_context = {'list_what': 'Category'}

    def get_queryset(self):
        user = self.request.user
        return Category.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Add Category'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Category created successfully!')
        return reverse_lazy('budget_section:category_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Update Category'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Category updated successfully!')
        return reverse_lazy('budget_section:category_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class CategoryDetailView(DetailView):
    model = Category
    template_name = 'budget_section/category_transaction_budget_detail.html'
    extra_context = {'detail_what': 'Category'}

    def get_queryset(self):
        user = self.request.user
        return Category.objects.filter(user=user)


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class CategoryDeleteView(DeleteView):
    model = Budget
    template_name = 'budget_section/category_transaction_budget_delete.html'
    extra_context = {'delete_what': 'Category'}

    def get_queryset(self):
        user = self.request.user
        return Category.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Category deleted successfully!')
        return reverse_lazy('budget_section:category_list')


@method_decorator(login_required, name='dispatch')
class TransactionListView(ListView):
    model = Transaction
    template_name = 'budget_section/category_transaction_budget_list.html'
    extra_context = {'list_what': 'Transaction'}

    def get_queryset(self):
        user = self.request.user
        return Transaction.objects.filter(user=user).order_by('-date')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class TransactionCreateView(CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Add Transaction'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Transaction created successfully!')
        return reverse_lazy('budget_section:transaction_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class TransactionUpdateView(UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'budget_section/category_transaction_budget_form.html'
    extra_context = {'header': 'Update Transaction'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Transaction updated successfully!')
        return reverse_lazy('budget_section:transaction_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class TransactionDetailView(DetailView):
    model = Transaction
    template_name = 'budget_section/category_transaction_budget_detail.html'
    extra_context = {'detail_what': 'Transaction'}

    def get_queryset(self):
        user = self.request.user
        return Transaction.objects.filter(user=user).order_by('-date')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class TransactionDeleteView(DeleteView):
    model = Transaction
    template_name = 'budget_section/category_transaction_budget_delete.html'
    extra_context = {'delete_what': 'Transaction'}

    def get_queryset(self):
        user = self.request.user
        return Transaction.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Transaction deleted successfully!')
        return reverse_lazy('budget_section:transaction_list')


@method_decorator(login_required, name='dispatch')
class GetSummaryTiles(TemplateView):
    template_name = 'budget_section/current_period.html'
    context_object_name = 'budget_data'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the budget ID from the URL parameters
        budget_slug = self.kwargs['slug']

        # Get the budget object
        budget = Budget.objects.get(slug=budget_slug)

        # Add the budget object to the context
        context['budget'] = budget

        # Get the total amount spent in the budget
        context['total_spent'] = Transaction.objects.filter(budget=budget).aggregate(Sum('amount'))['amount__sum'] or 0

        # Get the total number of transactions in the budget
        context['total_budget_transactions'] = Transaction.objects.filter(budget=budget).count()

        # Get the total budget amount
        context['total_budget'] = budget.amount

        # Get budget name
        context['budget_name'] = budget.name

        # Get budget start_date

templates/budget_section/category_transaction_budget_delete.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ delete_what }} - {{ object.id }}</h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>

    </div>
</div>
{% endblock %}

templates/budget_section/category_transaction_budget_detail.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">

    <div class="col-lg-8 mx-auto">
        <h1>{{detail_what}} {{object.slug}}</h1>
        <ul>
            {% if detail_what == 'Budget' %}
                <li>{{ object.name }}</li>
                <li>{{ object.amount }}</li>
                <li>{{ object.start_date|date:"Y/m/d" }}</li>
                <li>{{ object.end_date|date:"Y/m/d" }}</li>
            {% endif %}

            {% if detail_what == 'Category' %}
                  <li>{{ object.name }}</li>
                  <li>{{ object.description }}</li>
            {% endif %}

            {% if detail_what == 'Transaction' %}
            <li>{{ object.title }}</li>
            <li>{{ object.amount }}</li>
            <li>{{ object.category }}</li>
            <li>{{ object.budget }}</li>
            <li>{{ object.date|date:"Y/m/d" }}</li>
            <li>{{ object.notes }}</li>
            {% endif %}
        </ul>
        {% if detail_what == 'Budget' %}
        <a href="{% url 'budget_section:budget_update' object.slug %}">Update</a>
        <a href="{% url 'budget_section:budget_delete' object.slug %}">Delete</a>
        <a href="{% url 'budget_section:budget_summary' object.slug %}">View Dashboard</a>
        {% elif detail_what == 'Category' %}
        <a href="{% url 'budget_section:category_update' object.slug %}">Update</a>
        <a href="{% url 'budget_section:category_delete' object.slug %}">Delete</a>
        {% else %}
        <a href="{% url 'budget_section:transaction_update' object.slug %}">Update</a>
        <a href="{% url 'budget_section:transaction_delete' object.slug %}">Delete</a>
        {% endif %}


    </div>
</div>
{% endblock %}

templates/budget_section/category_transaction_budget_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ header }}</h1>

        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save">
        </form>

    </div>
</div>
{% endblock %}

templates/budget_section/category_transaction_budget_list.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">

            <h1>{{ list_what }} list</h1>

        </div>
    </div>

    <!-- Table-->
    <div class="row">
        <div class="col-lg-8 mx-auto table-responsive">

            {% if object_list %}
                <table id="list-table" class="table">
                    <thead>
                    <tr>
                        {% if list_what == 'Budget' %}
                        <th scope="col">Name</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Start date</th>
                        <th scope="col">End date</th>

                        {% elif list_what == 'Category' %}
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>

                        {% elif list_what == 'Transaction' %}
                        <th scope="col">Title</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Category</th>
                        <th scope="col">Budget</th>
                        <th scope="col">Date</th>
                        <th scope="col">Notes</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody id="table-body">
                    {% for object in object_list %}
                        <tr>
                            {% if list_what == 'Budget' %}
                            <td>{{ object.name }}</td>
                            <td>{{ object.amount }}</td>
                            <td>{{ object.start_date|date:"Y/m/d" }}</td>
                            <td>{{ object.end_date|date:"Y/m/d" }}</td>
                            {% endif %}

                            {% if list_what == 'Category' %}
                                  <td>{{ object.name }}</td>
                                  <td>{{ object.description }}</td>
                            {% endif %}

                             {% if list_what == 'Transaction' %}
                                  <td>{{ object.title }}</td>
                                  <td>{{ object.amount }}</td>
                                  <td>{{ object.category }}</td>
                                  <td>{{ object.budget }}</td>
                                  <td>{{ object.date|date:"Y/m/d" }}</td>
                                  <td>{{ object.notes }}</td>
                            {% endif %}
                            <td>
                                {% if list_what == 'Budget' %}
                                    <a href="{% url 'budget_section:budget_details' object.slug %}">
                                        {% elif list_what == 'Category' %}
                                        <a href="{% url 'budget_section:category_details' object.slug %}">
                                            {% else %}
                                            <a href="{% url 'budget_section:transaction_details' object.slug %}">
                                                {% endif %}
                                                <i class="fas fa-search-plus"></i>
                                            </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Nothing to show
            {% endif %}

        </div>
    </div>

{% endblock %}

{% block js %}
    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#list-table').DataTable(
                {
                    order: [[0, "desc"]],
                    columns: [
                        {name: "Date", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "End", orderable: true},
                        {% endif %}
                        {name: "Type", orderable: true},
                        {name: "Value", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "Repetition", orderable: true},
                        {% endif %}
                        {name: "Comment", orderable: true},
                        {name: "Details", orderable: false},
                    ]
                }
            );
        })
    </script>
{% endblock %}