benji_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('my_finances/', include('my_finances.urls')),
    path('accounts/', include('accounts.urls')),
    path('budget_section/', include('budget_section.urls')),
    path('savings_section/', include('savings_section.urls')),
    path('ai/', include('ai_features.urls')),
    path('tax/', include('tax_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

savings_section/urls.py
from django.urls import path

from .views import SavingsAccountListView, SavingsAccountCreateView, \
    SavingsAccountUpdateView, SavingsAccountDeleteView, SavingsAccountDetailView, SavingsAccountSummaryTiles, \
    DepositListView, DepositUpdateView, DepositDeleteView, DepositCreateView, DepositDetailView, \
    WithdrawalListView, WithdrawalDetailView, WithdrawalCreateView, WithdrawalUpdateView, WithdrawalDeleteView, \
    SavingsGoalDetailView, SavingsGoalListView, SavingsGoalCreateView, SavingsGoalDeleteView, SavingsGoalUpdateView

app_name = 'savings_section'

urlpatterns = [
    # SAVINGS_ACCOUNT URLS
    path('savings_accounts/', SavingsAccountListView.as_view(), name='savings_list'),
    path('savings_create/', SavingsAccountCreateView.as_view(), name='savings_create'),
    path('savings_update/<slug:slug>/', SavingsAccountUpdateView.as_view(), name='savings_update'),
    path('savings_detail/<slug:slug>/', SavingsAccountDetailView.as_view(), name='savings_detail'),
    path('savings_delete/<slug:slug>/', SavingsAccountDeleteView.as_view(), name='savings_delete'),

    # DEPOSIT URLS
    path('deposits/', DepositListView.as_view(), name='deposits_list'),
    path('deposit_create/', DepositCreateView.as_view(), name='deposit_create'),
    path('deposit_update/<slug:slug>/', DepositUpdateView.as_view(), name='deposit_update'),
    path('deposit_detail/<slug:slug>/', DepositDetailView.as_view(), name='deposit_detail'),
    path('deposit_delete/<slug:slug>/', DepositDeleteView.as_view(), name='deposit_delete'),

    # WITHDRAWAL URLS
    path('withdrawals/', WithdrawalListView.as_view(), name='withdrawals_list'),
    path('withdrawal_create/', WithdrawalCreateView.as_view(), name='withdrawal_create'),
    path('withdrawal_update/<slug:slug>/', WithdrawalUpdateView.as_view(), name='withdrawal_update'),
    path('withdrawal_detail/<slug:slug>/', WithdrawalDetailView.as_view(), name='withdrawal_detail'),
    path('withdrawal_delete/<slug:slug>/', WithdrawalDeleteView.as_view(), name='withdrawal_delete'),

    # SAVINGS_GOAL URLS
    path('savings_goals/', SavingsGoalListView.as_view(), name='savings_goals_list'),
    path('savings_goal_create/', SavingsGoalCreateView.as_view(), name='savings_goal_create'),
    path('savings_goal_update/<slug:slug>/', SavingsGoalUpdateView.as_view(), name='savings_goal_update'),
    path('savings_goal_detail/<slug:slug>/', SavingsGoalDetailView.as_view(), name='savings_goal_detail'),
    path('savings_goal_delete/<slug:slug>/', SavingsGoalDeleteView.as_view(), name='savings_goal_delete'),

    # DASHBOARD URLS
    path('savings_accounts/current_period/<slug:slug>', SavingsAccountSummaryTiles.as_view(), name='savings_summary'),

]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard')
]

savings_section/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify


# Create your models here.
class SavingsAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SavingsAccount name - {self.name}'


class Deposit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    savings = models.ForeignKey(SavingsAccount, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Deposit name - {self.name}'


class Withdrawal(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    savings = models.ForeignKey(SavingsAccount, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Withdrawal name - {self.name}'


class SavingsGoal(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    savings = models.ForeignKey(SavingsAccount, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True, unique=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SavingsGoal name - {self.name}'

savings_section/views.py
from django.shortcuts import render

# Create your views here.
import datetime
import json

from django.contrib import messages
from django.db.models import Count, Sum, Prefetch
from django.db.models.functions import Trunc
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django.urls import reverse_lazy
from .models import SavingsAccount, Deposit, Withdrawal, SavingsGoal
from .forms import SavingsGoalForm, WithdrawalForm, DepositForm, SavingsAccountForm


# Create your views here.

@method_decorator(login_required, name='dispatch')
class SavingsAccountListView(ListView):
    model = SavingsAccount
    template_name = 'savings_section/savings_section_list.html'
    paginate_by = 100
    extra_context = {'list_what': 'Savings'}

    def get_queryset(self):
        user = self.request.user
        return SavingsAccount.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class SavingsAccountCreateView(CreateView):
    model = SavingsAccount
    form_class = SavingsAccountForm
    template_name = 'savings_section/savings_section_form.html'
    extra_context = {'header': 'Add Savings'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Savings user created successfully!')
        return reverse_lazy('savings_section:savings_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class SavingsAccountUpdateView(UpdateView):
    model = SavingsAccount
    form_class = SavingsAccountForm
    template_name = 'savings_section/savings_section_form.html'
    extra_context = {'header': 'Update Savings'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Savings user updated successfully!')
        return reverse_lazy('savings_section:savings_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class SavingsAccountDetailView(DetailView):
    model = SavingsAccount
    template_name = 'savings_section/savings_section_detail.html'
    extra_context = {'detail_what': 'Savings'}

    def get_queryset(self):
        user = self.request.user
        return SavingsAccount.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class SavingsAccountDeleteView(DeleteView):
    model = SavingsAccount
    template_name = 'savings_section/savings_section_delete.html'
    extra_context = {'delete_what': 'Savings'}

    def get_queryset(self):
        user = self.request.user
        return SavingsAccount.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Savings user deleted successfully!')
        return reverse_lazy('savings_section:savings_list')


@method_decorator(login_required, name='dispatch')
class SavingsAccountSummaryTiles(TemplateView):
    template_name = 'savings_section/current_period.html'
    extra_context = {'display_what': 'Savings'}
    context_object_name = 'savings_data'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()

        # Get the savings slug from the URL parameters
        savings_slug = self.kwargs['slug']

        # Get savings object from slug
        savings_object = SavingsAccount.objects.select_related('user').get(slug=savings_slug)

        # Add the budget object to the context
        context['savings'] = savings_object

        # Savings name
        context['savings_name'] = savings_object.name

        # Savings balance
        context['savings_balance'] = savings_object.balance

        try:
            # Get savings goal amount
            savings_goal_object = SavingsGoal.objects.get(savings=savings_object)
            context['savings_goal'] = savings_goal_object
            context['savings_goal_amount'] = savings_goal_object.amount
        except SavingsGoal.DoesNotExist:
            # If savings goal does not exist, add an error message to the context
            context['error_message'] = 'Savings goal data not found.'

        # Calculate the total deposits made to the SavingsAccount
        total_deposits = savings_object.deposit_set.aggregate(total_deposits=Sum('amount'))['total_deposits'] or 0

        # Calculate the total withdrawals made from the SavingsAccount
        total_withdrawals = savings_object.withdrawal_set.aggregate(total_withdrawals=Sum('amount'))[
                                'total_withdrawals'] or 0

        # Calculate number of savings account for a user
        num_savings_account = SavingsAccount.objects.aggregate(num_savings_account=Count('id'))[
                                  'num_savings_account'] or 0

        # Calculate the number of savings goals for the user
        num_savings_goal = SavingsGoal.objects.aggregate(num_savings_goal=Count('id'))['num_savings_goal'] or 0

        # Calculate the number of deposits made to the SavingsAccount
        num_deposits = savings_object.deposit_set.aggregate(num_deposits=Count('id'))['num_deposits'] or 0

        # Calculate the number of withdrawals made from the SavingsAccount
        num_withdrawals = savings_object.withdrawal_set.aggregate(num_withdrawals=Count('id'))['num_withdrawals'] or 0

        # Calculate the current balance of the SavingsAccount
        current_balance = (savings_object.balance + total_deposits) - total_withdrawals

        # Calculate the percentage left to reach savings goal
        percentage_left = round(current_balance / savings_goal_object.amount, 2) * 100

        # Define the prefetch queryset
        savings_prefetch = Prefetch('savings', queryset=SavingsAccount.objects.only('id', 'name'))

        # Get deposit_withdrawal_history
        deposits = Deposit.objects.filter(savings=savings_object).prefetch_related('savings').annotate(
            timestamp=Trunc('created_at', 'month')
        ).values('created_at').annotate(
            total_amount=Sum('amount')
        ).order_by('created_at') or 0
        print(deposits)
        withdrawals = Withdrawal.objects.filter(savings=savings_object).prefetch_related('savings').annotate(
            timestamp=Trunc('created_at', 'month')
        ).values('created_at').annotate(
            total_amount=Sum('amount')
        ).order_by('created_at') or 0
        print(withdrawals)
        labels_deposit = []
        labels_withdrawal= []
        num_labels = ['Savings Accounts', 'Deposits', 'Withdrawals', 'Savings Goals']
        num_data = [num_savings_account, num_deposits, num_withdrawals, num_savings_goal]
        deposit_data = []
        withdrawal_data = []
        for deposit in deposits:
            labels_deposit.append(deposit['created_at'].strftime('%d %B'))
            deposit_data.append(float(deposit['total_amount']))
        for withdrawal in withdrawals:
            labels_withdrawal.append(withdrawal['created_at'].strftime('%d %B'))
            withdrawal_data.append(float(withdrawal['total_amount']))

        context['labels_deposit'] = json.dumps(labels_deposit)
        context['labels_withdrawal'] = json.dumps(labels_withdrawal)
        context['num_labels'] = json.dumps(num_labels)
        context['num_data'] = json.dumps(num_data)
        context['deposit_data'] = json.dumps(deposit_data)
        context['withdrawal_data'] = json.dumps(withdrawal_data)
        context['percentage_left'] = percentage_left
        context['today'] = datetime.datetime.today()
        context['total_deposits'] = total_deposits
        context['total_withdrawals'] = total_withdrawals
        context['total_savings_transactions'] = num_deposits + num_withdrawals
        context['num_deposits'] = num_deposits
        context['num_withdrawals'] = num_withdrawals
        context['current_balance'] = current_balance

        return context


@method_decorator(login_required, name='dispatch')
class DepositListView(ListView):
    model = Deposit
    template_name = 'savings_section/savings_section_list.html'
    paginate_by = 100
    extra_context = {'list_what': 'Deposit'}

    def get_queryset(self):
        user = self.request.user
        return Deposit.objects.filter(user=user).order_by('-id')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class DepositCreateView(CreateView):
    model = Deposit
    form_class = DepositForm
    template_name = 'savings_section/savings_section_form.html'
    extra_context = {'header': 'Add Deposit'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Deposit created successfully!')
        return reverse_lazy('savings_section:deposits_list')


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
class DepositUpdateView(UpdateView):
    model = Deposit
    form_class = DepositForm
    template_name = 'savings_section/savings_section_form.html'
    extra_context = {'header': 'Update Deposit'}

    def form_valid(self, form):

templates/savings_section/savings_section_delete.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ delete_what }} - {{ object.id }}</h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>

    </div>
</div>
{% endblock %}

templates/savings_section/savings_section_detail.html
{% extends 'base2.html' %}
{% block content %}
<div class="row">

    <div class="col-lg-8 mx-auto">
        <h1>{{detail_what}} {{object.slug}}</h1>
        <ul>
            {% if detail_what == 'Savings' %}
                <li>{{ object.name }}</li>
                <li>{{ object.balance }}</li>
                <li>{{ object.description }}</li>
                <li>{{ object.created_at|date:"Y/m/d" }}</li>
            {% endif %}
            
            {% if detail_what == 'Deposit' %}
              <li>{{ object.name }}</li>
              <li>{{ object.amount }}</li>
              <li>{{ object.description }}</li>
              <li>{{ object.created_at|date:"Y/m/d" }}</li>
            {% endif %}

             {% if detail_what == 'Withdrawal' %}
              <li>{{ object.name }}</li>
              <li>{{ object.amount }}</li>
              <li>{{ object.description }}</li>
              <li>{{ object.created_at|date:"Y/m/d" }}</li>
            {% endif %}

            {% if detail_what == 'SavingsGoal' %}
              <li>{{ object.name }}</li>
              <li>{{ object.amount }}</li>
              <li>{{ object.description }}</li>
              <li>{{ object.created_at|date:"Y/m/d" }}</li>
            {% endif %}
            
        </ul>
        {% if detail_what == 'Savings' %}
        <a href="{% url 'savings_section:savings_update' object.slug %}">Update</a>
        <a href="{% url 'savings_section:savings_delete' object.slug %}">Delete</a>
        <a href="{% url 'savings_section:savings_summary' object.slug %}">View Dashboard</a>
        {% elif detail_what == 'Deposit' %}
         <a href="{% url 'savings_section:deposit_update' object.slug %}">Update</a>
        <a href="{% url 'savings_section:deposit_delete' object.slug %}">Delete</a>
        {% elif details_what == 'Withdrawal' %}
         <a href="{% url 'savings_section:withdrawal_update' object.slug %}">Update</a>
        <a href="{% url 'savings_section:withdrawal_delete' object.slug %}">Delete</a>
        {% elif detail_what == 'SavingsGoal' %}
         <a href="{% url 'savings_section:savings_goal_update' object.slug %}">Update</a>
        <a href="{% url 'savings_section:savings_goal_delete' object.slug %}">Delete</a>
        {% endif %}


    </div>
</div>
{% endblock %}

templates/savings_section/savings_section_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1>{{ header }}</h1>

        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save">
        </form>

    </div>
</div>
{% endblock %}

templates/savings_section/savings_section_list.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">

            <h1>{{ list_what }} list</h1>

        </div>
    </div>

    <!-- Table-->
    <div class="row">
        <div class="col-lg-8 mx-auto table-responsive">

            {% if object_list %}
                <table id="list-table" class="table">
                    <thead>
                    <tr>
                        {% if list_what == 'Savings' %}
                        <th scope="col">Name</th>
                        <th scope="col">Balance</th>
                        <th scope="col">Description</th>
                         <th scope="col">Created on</th>

                        {% elif list_what == 'Deposit' %}
                        <th scope="col">Name</th>
                        <th scope="col">amount</th>
                        <th scope="col">Savings</th>
                        <th scope="col">Description</th>
                         <th scope="col">Created on</th>

                        {% elif list_what == 'Withdrawal' %}
                        <th scope="col">Name</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Savings</th>
                        <th scope="col">Description</th>
                        <th scope="col">Created on</th>

                        {% elif list_what == 'SavingsGoal' %}
                        <th scope="col">Name</th>
                        <th scope="col">Amount</th>
                        <th scope="col">SAvings</th>
                        <th scope="col">Description</th>
                        <th scope="col">Created on</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody id="table-body">
                    {% for object in object_list %}
                        <tr>
                            {% if list_what == 'Savings' %}
                            <td>{{ object.name }}</td>
                            <td>{{ object.balance }}</td>
                            <td>{{ object.description }}</td>
                            <td>{{ object.created_at|date:"Y/m/d" }}</td>
                            {% endif %}

                            {% if list_what == 'Deposit' %}
                                  <td>{{ object.name }}</td>
                                  <td>{{ object.amount }}</td>
                                    <td>{{ object.savings }}</td>
                                  <td>{{ object.description }}</td>
                                  <td>{{ object.created_at|date:"Y/m/d" }}</td>
                            {% endif %}

                             {% if list_what == 'Withdrawal' %}
                                  <td>{{ object.name }}</td>
                                  <td>{{ object.amount }}</td>
                                  <td>{{ object.savings }}</td>
                                    <td>{{ object.description }}</td>
                                  <td>{{ object.created_at|date:"Y/m/d" }}</td>
                            {% endif %}

                            {% if list_what == 'SavingsGoal' %}
                                  <td>{{ object.name }}</td>
                                  <td>{{ object.amount }}</td>
                                  <td>{{ object.savings }}</td>
                                    <td>{{ object.description }}</td>
                                  <td>{{ object.created_at|date:"Y/m/d" }}</td>
                            {% endif %}
                            <td>
                                {% if list_what == 'Savings' %}
                                    <a href="{% url 'savings_section:savings_detail' object.slug %}">
                                {% elif list_what == 'Deposit' %}
                                    <a href="{% url 'savings_section:deposit_detail' object.slug %}">
                                {% elif list_what == 'Withdrawal' %}
                                    <a href="{% url 'savings_section:withdrawal_detail' object.slug %}">
                                {% else %}
                                    <a href="{% url 'savings_section:savings_goal_detail' object.slug %}">
                                {% endif %}
                                    <i class="fas fa-search-plus"></i>
                                            </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Nothing to show
            {% endif %}

        </div>
    </div>

{% endblock %}

{% block js %}
    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#list-table').DataTable(
                {
                    order: [[0, "desc"]],
                    columns: [
                        {name: "Date", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "End", orderable: true},
                        {% endif %}
                        {name: "Type", orderable: true},
                        {name: "Value", orderable: true},
                        {% if list_what != 'Balance' %}
                            {name: "Repetition", orderable: true},
                        {% endif %}
                        {name: "Comment", orderable: true},
                        {name: "Details", orderable: false},
                    ]
                }
            );
        })
    </script>
{% endblock %}